### PR TITLE
Fix unittest and change pinned packages

### PR DESCRIPTION
**Pull request by urshulgi**
Related to #19 #18

- Fix unittest
- Update readme
- Update TODO
- Pin Pillow to lower version 9.1.0
- Update requires to major than version instead of static version

All tests are passing:
```
python -m unittest discover ./tests
/opt/homebrew/Caskroom/miniconda/base/envs/flask-image-resizer/lib/python3.10/site-packages/flask/app.py:415: UserWarning: Current server name 'localhost:8000' doesn't match configured server name 'localhost'
  return self.url_map.bind_to_environ(
/Users/nickbaldallo/github-projects/Flask-Image-Resizer/flask_image_resizer/core.py:412: ResourceWarning: unclosed file <_io.BufferedReader name='/Users/nickbaldallo/github-projects/Flask-Image-Resizer/tests/assets/cc.png'>
  image_format = get_image_format(path)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/opt/homebrew/Caskroom/miniconda/base/envs/flask-image-resizer/lib/python3.10/unittest/case.py:549: ResourceWarning: unclosed file <_io.BufferedReader name='/tmp/flask-images/fc/fc9579e51a785c9e5dd143240d883b9c.png'>
  method()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
./Users/nickbaldallo/github-projects/Flask-Image-Resizer/tests/test_build_url.py:31: ResourceWarning: unclosed file <_io.BufferedReader name='/tmp/flask-images/fc/fc9579e51a785c9e5dd143240d883b9c.png'>
  response = self.client.get(url)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/Users/nickbaldallo/github-projects/Flask-Image-Resizer/tests/test_build_url.py:31: ResourceWarning: unclosed file <_io.BufferedReader name='/tmp/flask-images/a4/a428076e66b9c4a943391ed5b942383f.png'>
  response = self.client.get(url)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/Users/nickbaldallo/github-projects/Flask-Image-Resizer/tests/test_build_url.py:31: ResourceWarning: unclosed file <_io.BufferedReader name='/tmp/flask-images/52/521bd6bdf193bd07cb56b518c09963d2.png'>
  response = self.client.get(url)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/opt/homebrew/Caskroom/miniconda/base/envs/flask-image-resizer/lib/python3.10/unittest/case.py:549: ResourceWarning: unclosed file <_io.BufferedReader name='/tmp/flask-images/78/78627282d33f5c7ee40ee55bc41dfff9.png'>
  method()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
../Users/nickbaldallo/github-projects/Flask-Image-Resizer/flask_image_resizer/core.py:291: DeprecationWarning: LANCZOS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  return image.resize((size.width, size.height), Image.LANCZOS)
../Users/nickbaldallo/github-projects/Flask-Image-Resizer/flask_image_resizer/core.py:412: ResourceWarning: unclosed file <_io.BufferedReader name='/tmp/flask-images/d9e12899c916d19ce7166a7f91025b87'>
  image_format = get_image_format(path)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/opt/homebrew/Caskroom/miniconda/base/envs/flask-image-resizer/lib/python3.10/unittest/case.py:549: ResourceWarning: unclosed file <_io.BufferedReader name='/tmp/flask-images/e9/e968a63e777ccc25e36419c7e2caaac6.jpeg'>
  method()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
./opt/homebrew/Caskroom/miniconda/base/envs/flask-image-resizer/lib/python3.10/urllib/parse.py:644: ResourceWarning: unclosed <ssl.SSLSocket [closed] fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0>
  for item in bits[1:]:
ResourceWarning: Enable tracemalloc to get the object allocation traceback
...../Users/nickbaldallo/github-projects/Flask-Image-Resizer/flask_image_resizer/transform.py:20: DeprecationWarning: EXTENT is deprecated and will be removed in Pillow 10 (2023-07-01). Use Transform.EXTENT instead.
  self.flag = getattr(Image, self[0].upper())
..........
----------------------------------------------------------------------
Ran 21 tests in 0.628s

OK
```

### CODE REVIEW

**Comment by urshulgi** [comment]
The demo only works with 2.2.4 or higher because of werkzeug?

```
python -m flask --app main run
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/flask-image-resizer/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/flask-image-resizer/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/flask-image-resizer/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/flask-image-resizer/lib/python3.10/site-packages/flask/__init__.py", line 5, in <module>
    from .app import Flask as Flask
  File "/opt/homebrew/Caskroom/miniconda/base/envs/flask-image-resizer/lib/python3.10/site-packages/flask/app.py", line 30, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/opt/homebrew/Caskroom/miniconda/base/envs/flask-image-resizer/lib/python3.10/site-packages/werkzeug/urls.py)
```

That version was released april last year. Should we use that version for the package as well as minimum requirement?
